Removed space from in front of '=>' in feedback messages

diff --git a/delphyne b/delphyne
--- a/delphyne
+++ b/delphyne
@@ -116,7 +116,7 @@ display_error() {
     errstr="$(clean_json < "${bodypath}" | get_json_string_value error)"
     if [ -n "${errstr}" ]; then
       parsed_error=true
-      echo " => ${errstr}" >&2
+      echo "=> ${errstr}" >&2
     else
       # Array of error messages?
       errstr="$(clean_json < "${bodypath}" | get_json_array_value errors)"
@@ -124,7 +124,7 @@ display_error() {
         parsed_error=true
         get_json_array_as_lines <<< "${errstr}" | while read -r line; do
           if [ -n "${line}" ]; then
-            echo " => ${line}" >&2
+            echo "=> ${line}" >&2
           fi
         done
       fi
@@ -133,7 +133,7 @@ display_error() {
 
   # If we failed to parse the error message, display the full response
   if [ "$parsed_error" = false ] ; then
-    echo " => An error occurred while making request" >&2
+    echo "=> An error occurred while making request" >&2
     echo >&2
     echo "Response:" >&2
     cat "${headerspath}" >&2
@@ -213,7 +213,7 @@ display_zones() {
 display_message() {
   message="$(echo "${1}" | clean_json | get_json_string_value message)"
   if [ -n "${message}" ]; then
-    echo " => ${message}" >&2
+    echo "=> ${message}" >&2
   fi
 }
 
